{
 "title": "New dashboard",
 "time": { "from": "2023-09-05T08:07:59.072Z", "to": "2023-09-05T10:25:45.096Z" },
 "panels": [
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(node_load1) by (instance)" },
    { "expr": "avg(node_load5) by (instance)" },
    { "expr": "avg(node_load15) by (instance)" }
   ]
  },
  {
   "title": "Свободная память",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Свободное место",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_filesystem_size_bytes" }
   ]
  }
 ]
}